# Generated by Django 3.2.2 on 2021-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBy', models.CharField(max_length=200)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ProductsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productBy', models.CharField(max_length=200)),
                ('productImage', models.ImageField(upload_to='')),
                ('productName', models.CharField(max_length=200)),
                ('productCount', models.IntegerField()),
                ('productLikes', models.IntegerField()),
                ('productPrice', models.IntegerField()),
                ('comments', models.ManyToManyField(to='products.Comments')),
                ('tags', models.ManyToManyField(to='products.Tags')),
            ],
            options={
                'db_table': 'ProductsCollection',
            },
        ),
        migrations.AddIndex(
            model_name='productscollection',
            index=models.Index(fields=['productName'], name='ProductsCol_product_9547fe_idx'),
        ),
    ]
